#spring.application.name=quanly-sotietkiem
#spring.data.mongodb.uri=mongodb://localhost:27017/quanly_sotietkiem
spring.application.name=quanly-sotietkiem
spring.data.mongodb.uri=mongodb+srv://Final_Project:kakakaka195@cluster0.wqltcnw.mongodb.net/quanly_sotietkiem?retryWrites=true&w=majority&appName=Final_Project_Java